// decks
const ACTIVATE_DECKS_LOADING_STATE = 'ACTIVATE_DECKS_LOADING_STATE';
const FETCH_DECKS_SUCCESS = 'FETCH_DECKS_SUCCESS';
const FETCH_DECK_SUCCESS = 'FETCH_DECK_SUCCESS';

export { ACTIVATE_DECKS_LOADING_STATE, FETCH_DECKS_SUCCESS, FETCH_DECK_SUCCESS };
